services:
  db:
    image: pgvector/pgvector:pg16
    container_name: curated-content-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-curated_content_portal}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-curated_content_portal}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - curated-network
    env_file:
      - ./.secrets/.env.local

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: curated-content-app
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - curated-network
    env_file:
      - ./.secrets/.env.local

  redis:
    image: redis:7-alpine
    container_name: curated-content-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - curated-network

volumes:
  postgres_data:
  redis_data:

networks:
  curated-network:
    driver: bridge